CREATE TABLE STUDENTDETAILS(ADNO VARCHAR2(20) PRIMARY KEY,SNAME VARCHAR2(100) NOT NULL,
			    BRANCH VARCHAR2(8) NOT NULL,YEAR VARCHAR2(6) NOT NULL,DATEOFJOIN DATE,
			    YEAROFJOIN VARCHAR2(8),STATUS VARCHAR2(10),CDATE DATE,
			    QUESTION VARCHAR2(2) ,ANSWER VARCHAR2(100),PASSWORD VARCHAR2(30)
			    );

CREATE TABLE STAFF( LID VARCHAR2(10) PRIMARY KEY,
		    LNAME VARCHAR2(100) NOT NULL,
		    DEPT VARCHAR2(40) NOT NULL,
                    JOININGDATE DATE,
                    TEACHING VARCHAR2(5),
		    STATUS VARCHAR2(6),
                    PASSWORD VARCHAR2(30),
		    QUESTION VARCHAR2(3),
		    ANSWER VARCHAR2(100),	
		    CDATE DATE	
                   );


CREATE TABLE LIBRARY( ACESSNO VARCHAR2(8) PRIMARY KEY,BOOKNAME VARCHAR2(100),AUTHOR1S VARCHAR2(100),AUTHOR1F VARCHAR2(100),
                      AUTHOR2S VARCHAR2(100),AUTHOR2F VARCHAR2(100),AUTHOR3S VARCHAR2(100),AUTHOR3F VARCHAR2(100),
		      AUTHOR4S VARCHAR2(100),AUTHOR4F VARCHAR2(100),AUTHOR5S VARCHAR2(100),AUTHOR5F VARCHAR2(100),	
                      PUBLISHER VARCHAR2(100),EDITION VARCHAR2(5),ISBN VARCHAR2(20),NOTE VARCHAR2(100),         
		      DESCPRTN VARCHAR2(100),PHY_MEDM VARCHAR2(30),PLACE VARCHAR2(30),YEAR VARCHAR2(10),
		      SUBJECT1 VARCHAR2(30),SUBJECT2 VARCHAR2(30),SUBJECT3  VARCHAR2(30),ACESSDATE DATE,ISSUED VARCHAR2(2),
		      STATUS VARCHAR2(20),VOLUME VARCHAR2(10),SERIES VARCHAR2(10),SUPPLIER VARCHAR2(100),PRICE VARCHAR2(10),
		      BILLNO VARCHAR2(20),CALLNO VARCHAR2(20),BILLDATE DATE,WITHDRAW_DATE DATE
                    );

CREATE TABLE CDDETAILS( CDCODE VARCHAR2(20) PRIMARY KEY,CDSERIAL VARCHAR2(75),BKANO VARCHAR2(20),CDVERSION VARCHAR2(8),
                        CDNAME VARCHAR2(100),CDTYPE VARCHAR2(30),SUBJECT VARCHAR2(100),CDSTATUS VARCHAR2(100),RDATE DATE,NOTE LONG,
			ADATE DATE,MZACNO VARCHAR2(20),ISSUED VARCHAR2(2),STATUS VARCHAR2(20));

CREATE TABLE MZDETAILS( ACCESSNO VARCHAR2(10) PRIMARY KEY,MZNAME VARCHAR2(100),VOLUME VARCHAR2(10),MZCODE VARCHAR2(10),
                        SOURCE VARCHAR2(30),PAGES VARCHAR2(8),SUPPLEMENT VARCHAR2(100),CDS VARCHAR2(20),
			PRICE VARCHAR2(10),PCITY VARCHAR2(10),PERIOD VARCHAR2(10),RDATE DATE,ADATE DATE,
			REMARKS VARCHAR2(100),ISSUED VARCHAR2(2),STATUS VARCHAR2(20)
		      );


CREATE TABLE TRANSACTION_HISTORY( CODE VARCHAR2(8), CDCODE VARCHAR2(20), MZCODE VARCHAR2(20),
                          ADNO VARCHAR2(20),STATUS VARCHAR2(10),CDATE DATE,
                          LID VARCHAR2(20),VALUE VARCHAR2(5),
			  IDATE DATE,RDATE DATE,
			  FINEAMOUNT VARCHAR2(10),FINE_PAID VARCHAR2(10),
			  FDATE DATE,	
			  REASON LONG
			);

CREATE VIEW STUDENT_HISTORY AS SELECT STD.ADNO,STD.SNAME,STD.BRANCH,LIB.ACESSNO,LIB.AUTHOR1S||LIB.AUTHOR1F AUTHOR,
LIB.BOOKNAME,BD.IDATE,BD.RDATE FROM STUDENTDETAILS STD,LIBRARY LIB,
BOOKDETAILS BD WHERE STD.ADNO=BD.ADNO AND LIB.ACESSNO=BD.CODE;

CREATE VIEW STAFF_HISTORY AS SELECT STD.LID,STD.LNAME,STD.DEPT,LIB.ACESSNO,LIB.AUTHOR1S||LIB.AUTHOR1F AUTHOR,
LIB.BOOKNAME,BD.IDATE,BD.RDATE FROM STAFF STD,LIBRARY LIB,
BOOKDETAILS BD WHERE STD.LID=BD.LID AND LIB.ACESSNO=BD.CODE;



CREATE VIEW STUDENT_HISTORY2 AS SELECT STD.ADNO,STD.SNAME,STD.BRANCH,CD.CDCODE,CD.CDNAME,
CD.CDVERSION,BD.IDATE,BD.RDATE FROM STUDENTDETAILS STD,CDDETAILS CD,
BOOKDETAILS BD WHERE STD.ADNO=BD.ADNO AND CD.CDCODE=BD.CDCODE;

CREATE VIEW STAFF_HISTORY2 AS SELECT STD.LID,STD.LNAME,STD.DEPT,CD.CDCODE,CD.CDNAME,
CD.CDVERSION,BD.IDATE,BD.RDATE FROM STAFF STD,CDDETAILS CD,
BOOKDETAILS BD WHERE STD.LID=BD.LID AND CD.CDCODE=BD.CDCODE;




CREATE VIEW STUDENT_HISTORY3 AS SELECT STD.ADNO,STD.SNAME,STD.BRANCH,MZ.ACCESSNO,MZ.MZNAME,
MZ.VOLUME,BD.IDATE,BD.RDATE FROM STUDENTDETAILS STD,MZDETAILS MZ,
BOOKDETAILS BD WHERE STD.ADNO=BD.ADNO AND MZ.ACCESSNO=BD.MZCODE;

CREATE VIEW STAFF_HISTORY3 AS SELECT STD.LID,STD.LNAME,STD.DEPT,MZ.ACCESSNO,MZ.MZNAME,
MZ.VOLUME,BD.IDATE,BD.RDATE FROM STAFF STD,MZDETAILS MZ,
BOOKDETAILS BD WHERE STD.LID=BD.LID AND MZ.ACCESSNO=BD.MZCODE;




CREATE TABLE BKTRANSACTION ( CODE VARCHAR2(8) ,
			     ADNO VARCHAR2(20) NOT NULL,
			     IDATE DATE,RDATE DATE,NO_OF_REN VARCHAR2(2)
                           );


CREATE TABLE CDTRANSACTION ( CDCODE VARCHAR2(20),
			     ADNO VARCHAR2(20) NOT NULL,
			     IDATE DATE,RDATE DATE,NO_OF_REN VARCHAR2(2)
			   );

CREATE TABLE CDTRANSACTION1 ( CDCODE VARCHAR2(20),
                              LID VARCHAR2(20) NOT NULL,
			      IDATE DATE,RDATE DATE 
			    );			

CREATE TABLE BKTRANSACTION1( CODE VARCHAR2(20),
			     LID VARCHAR2(10) NOT NULL, 
			     IDATE DATE, RDATE DATE
			   );

CREATE TABLE MZTRANSACTION1( MZCODE VARCHAR2(20),
			     LID VARCHAR2(10) NOT NULL,
			     IDATE DATE, RDATE DATE
			   );


CREATE TABLE MZTRANSACTION ( MZCODE VARCHAR2(8) ,
			     ADNO VARCHAR2(20) NOT NULL,
			     IDATE DATE,RDATE DATE,NO_OF_REN VARCHAR2(2)
			   );


CREATE TABLE SHEDULE(DAY VARCHAR2(20),TIME VARCHAR2(20),BRANCH VARCHAR2(8),YEAR VARCHAR2(8),
 		      PRIMARY KEY(BRANCH,YEAR)	 	);

CREATE TABLE KEYCONSTRAINTS(ID NUMBER(2) PRIMARY KEY ,MIN_BOOKS NUMBER(3),MAX_BOOKS NUMBER(3),
				BOOK_HOLDING_PERIOD NUMBER(3), MIN_CDS NUMBER(3),
				MAX_CDS NUMBER(3),CD_HOLDING_PERIOD NUMBER(3),
				MIN_MZS NUMBER(3),MAX_MZS NUMBER(3),MZ_HOLDING_PERIOD NUMBER(3),
				RENEIVAL_PERIOD_BOOK NUMBER(3),NO_OF_RENEIVALS_BOOK NUMBER(3),
				RENEIVAL_PERIOD_CD NUMBER(3),NO_OF_RENEIVALS_CD NUMBER(3),
				RENEIVAL_PERIOD_MZ NUMBER(3),NO_OF_RENEIVALS_MZ NUMBER(3),
				FINE_BOOK NUMBER(5),FINE_CD NUMBER(5),FINE_MZ NUMBER(5),
				FROM_HOLD DATE,TO_HOLD DATE,	
				IMAGE_PATH VARCHAR2(20));


CREATE  TABLE STD_RESERVE( ADNO VARCHAR2(20),
			   BOOKNAME VARCHAR2(100),
                           AUTHOR1 VARCHAR2(200),
			   AUTHOR2 VARCHAR2(200), 
			   AUTHOR3 VARCHAR2(200),
			   CDNAME  VARCHAR2(100),
			   SUBJECT1 VARCHAR2(100),
			   VERSION  VARCHAR2(10),
			   MZNAME  VARCHAR2(100),
			   MONTH  VARCHAR2(10),
			   VOLUME VARCHAR2(100),	
			   PUBLISHER VARCHAR2(100),
			   IDATE DATE,TIME VARCHAR2(15)
			 );		

CREATE  TABLE STF_RESERVE( LID VARCHAR2(20),
			   BOOKNAME VARCHAR2(100),
                           AUTHOR1 VARCHAR2(200),
			   AUTHOR2 VARCHAR2(200), 
			   AUTHOR3 VARCHAR2(200),
			   CDNAME  VARCHAR2(100),
			   SUBJECT1 VARCHAR2(100),
			   VERSION  VARCHAR2(10),
			   MZNAME  VARCHAR2(100),
			   MONTH  VARCHAR2(20),
			   VOLUME VARCHAR2(100),	
			   PUBLISHER VARCHAR2(100),
			   IDATE DATE,TIME VARCHAR2(15)
			 );
